Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('pizzas.urls')),
]

"""
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    ...]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
"""

pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name = 'index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/',views.pizza, name='pizza'),
    path('new_comment/<int:pizza_id>/', views.new_comment, name='new_comment'),
    
    #path('upload/', views.image_upload_view)
    
]

pizzas/models.py
from django.db import models

# Create your models here.

class Pizza(models.Model):
    name=models.CharField(max_length=50)
    

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza=models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name=models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza=models.ForeignKey(Pizza, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

"""
class Image(models.Model):
    title = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.title
"""

pizzas/forms.py
from django import forms
from .models import Pizza, Topping, Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        label = {'text: ':''}

        widgets = {'text': forms.Textarea(attrs={'cols':50})}
"""
from django import forms
from .models import Image


class ImageForm(forms.ModelForm):
    #Form for the image model
    class Meta:
        model = Image
        fields = ('title', 'image')
"""

pizzas/views.py
from django.shortcuts import render, redirect
from .models import Pizza, Topping, Comment
from .forms import CommentForm

# Create your views here.
def index(request):
    """The homepage for our Pizzeria"""
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.order_by('name')

    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('name')
    comments = pizza.comment_set.order_by('-date_added')

    context = {'pizza':pizza, 'toppings':toppings, 'comments':comments}
    return render(request, 'pizzas/pizza.html', context)

def new_comment(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    comments = pizza.comment_set.order_by('-date_added')

    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)
    
    context = {'form':form, 'pizza':pizza, 'comments':comments}
    return render(request, 'pizzas/new_comment.html', context)

"""
from .forms import ImageForm

def image_upload_view(request):
    #Process images uploaded by users
    if request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # Get the current instance object to display in the template
            img_obj = form.instance
            return render(request, 'index.html', {'form': form, 'img_obj': img_obj})
    else:
        form = ImageForm()
    return render(request, 'index.html', {'form': form})
"""

pizzas/templates/pizzas/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title>Dave's Pizzeria</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'pizzas:index' %}">
            Dave's Pizzeria</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'pizzas:pizzas'%}">
                        Menu</a>
                </li>
            </ul>
        </div>
    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
</body>

</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block page_header %}
<div class="jumbotron">
    <hi class="display-3">Welcome to Dave's Pizzeria!</hi>

    <p class="lead">Our pizzas are as invisible as they are delicious! <br>
        Browse our menu now.</p>
</div>
{% endblock page_header %}

<!--
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
</form>

{% if img_obj %}
<h3>Succesfully uploaded : {{img_obj.title}}</h3>
<img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">
{% endif %}
-->

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a></p>

<p> Add a new comment</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>

    {% csrf_token %}
    {{ form.as_p }}

    <button name='submit'>Add comment</button>
</form>

{% endblock content %}

pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Pizza: {{ pizza }}
</p>

<ul>

    {% for topping in toppings %}
    <li>
        <p>{{ topping.name }}</p>
    </li>
    {% empty %}
    <li>This pizza only has cheese and sauce.</li>
    {% endfor %}
</ul>

<p>
    <a href="{% url 'pizzas:new_comment' pizza.id %}">Add new comment</a>
</p>

<p>Comments:</p>

<ul>

    {% for c in comments.all %}
    <li>
        <p>{{ c.text }}</p>
    </li>
    {% endfor %}

</ul>

{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Available Pizzas
</p>

<ul>

    {% for pizza in pizzas %}
    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </li>
    {% empty %}
    <li>There are currently no pizzas available.</li>
    {% endfor %}

</ul>

{% endblock content %}